name: Auto Comment on Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment based on label
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const labels = context.payload.issue.labels.map(label => label.name);
            const owner = context.repo.owner;
            
            let comment = '';
            
            if (labels.includes('bug')) {
              comment = `Thank you. We will fix it. Best regards, ${owner}.`;
            } else if (labels.includes('feature')) {
              comment = `Thank you, we will consider to include this feature. Best regards, ${owner}.`;
            } else if (labels.includes('discussion')) {
              comment = `Happy to discuss this topic with you. Best regards, ${owner}.`;
            }
            
            if (comment) {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: comment
              });
            }